In [ ]:
import polars as pl

df = pl.read_parquet("../data/gold/gold_movies.parquet")
df = df.group_by(df.columns).first()
print(print(df.head(10)))

shape: (10, 49)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ master_id ┆ tmdb_id ┆ title      ┆ original_ ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_ri │
│ ---       ┆ ---     ┆ ---        ┆ title     ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ght       │
│ u32       ┆ i64     ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆         ┆            ┆ str       ┆   ┆ null      ┆ null      ┆           ┆ str       │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 8242      ┆ 458353  ┆ High Heel  ┆ High Heel ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Homicide   ┆ Homicide  ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 9303      ┆ 11525   ┆ Lawnmower  ┆ Lawnmower ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Man 2:     ┆ Man 2:    ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Beyond     ┆ Beyond    ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Cybers…    ┆ Cybers…   ┆   ┆           ┆           ┆ com…      ┆           │
│ 8351      ┆ 4290    ┆ Supergator ┆ Supergato ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆ r         ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 2290      ┆ 13312   ┆ Inside     ┆ À l'intér ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆ ieur      ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 7194      ┆ 172372  ┆ Hate Crime ┆ Hate      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆ Crime     ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 9363      ┆ 73262   ┆ Hell       ┆ Hell      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 1585      ┆ 146852  ┆ The Brain  ┆ The Brain ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 8462      ┆ 754983  ┆ Voices     ┆ Voices    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 5517      ┆ 993784  ┆ Lisa Frank ┆ Lisa Fran ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ enstein    ┆ kenstein  ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 60        ┆ 1242011 ┆ Together   ┆ Together  ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
None

In [21]:
df.schema

Schema([('master_id', UInt32),
        ('tmdb_id', Int64),
        ('title', String),
        ('original_title', String),
        ('overview', String),
        ('release_date', String),
        ('vote_average', Float64),
        ('vote_count', Int32),
        ('popularity', Float64),
        ('original_language', String),
        ('adult', Boolean),
        ('poster_path', String),
        ('backdrop_path', String),
        ('genre_ids', List(Int64)),
        ('source', String),
        ('year', Int32),
        ('title_clean', String),
        ('title_key', String),
        ('imdb_id', String),
        ('title_imdb', String),
        ('genres', String),
        ('cast', List(String)),
        ('source_imdb', String),
        ('title_clean_imdb', String),
        ('title_kaggle', String),
        ('overview_kaggle', String),
        ('tagline', String),
        ('genres_kaggle', String),
        ('release_date_kaggle', String),
        ('vote_average_kaggle', Float64),
        ('popularity_kaggle', Float64),
        ('source_kaggle', String),
        ('title_clean_kaggle', String),
        ('movieId', Int32),
        ('title_ml', String),
        ('genres_ml', String),
        ('avg_rating', Float64),
        ('num_ratings', Int32),
        ('source_ml', String),
        ('title_clean_ml', String),
        ('fuzzy_imdb', String),
        ('fuzzy_kaggle', String),
        ('fuzzy_movielens', String),
        ('title_right', String),
        ('tomatometer_score', Null),
        ('audience_score', Null),
        ('critics_consensus', Null),
        ('url', String),
        ('source_right', String)])

In [22]:
df.describe()

shape: (9, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ master_id ┆ tmdb_id   ┆ title     ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_r │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ight     │
│ str       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 9837.0    ┆ 9837.0    ┆ 9837      ┆ … ┆ 0.0       ┆ 0.0       ┆ 9837      ┆ 9837     │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 9837.0    ┆ 9837.0    ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 4917.4559 ┆ 426810.84 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 32        ┆ 3042      ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2841.3982 ┆ 465714.23 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 56        ┆ 3524      ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 17.0      ┆ #AMFAD:   ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_t │
│           ┆           ┆           ┆ All My    ┆   ┆           ┆           ┆ ww.rotten ┆ omatoes  │
│           ┆           ┆           ┆ Friends   ┆   ┆           ┆           ┆ tomatoes. ┆          │
│           ┆           ┆           ┆ Are Dea…  ┆   ┆           ┆           ┆ com…      ┆          │
│ 25%       ┆ 2458.0    ┆ 42487.0   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 4914.0    ┆ 241843.0  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 7376.0    ┆ 697799.0  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 9846.0    ┆ 1.701736e ┆ 裸尸痕    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_t │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ omatoes  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ tomatoes. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ com…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
df.group_by("master_id").len().filter(pl.col("len") > 1)

shape: (10, 2)
┌───────────┬─────┐
│ master_id ┆ len │
│ ---       ┆ --- │
│ u32       ┆ u32 │
╞═══════════╪═════╡
│ 3174      ┆ 2   │
│ 7256      ┆ 2   │
│ 3594      ┆ 2   │
│ 4368      ┆ 2   │
│ 742       ┆ 2   │
│ 287       ┆ 2   │
│ 7099      ┆ 2   │
│ 4878      ┆ 2   │
│ 2134      ┆ 2   │
│ 5978      ┆ 2   │
└───────────┴─────┘

In [25]:
dups = (
    df.group_by("master_id")
      .len()
      .filter(pl.col("len") > 1)
      .select("master_id")
)

df.filter(pl.col("master_id").is_in(dups["master_id"]))

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_27148\1464026237.py:8: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  df.filter(pl.col("master_id").is_in(dups["master_id"]))

shape: (20, 49)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ master_id ┆ tmdb_id ┆ title      ┆ original_ ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_ri │
│ ---       ┆ ---     ┆ ---        ┆ title     ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ght       │
│ u32       ┆ i64     ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆         ┆            ┆ str       ┆   ┆ null      ┆ null      ┆           ┆ str       │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3594      ┆ 178674  ┆ Esprit     ┆ 陰陽愛    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ D'Amour    ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 4878      ┆ 39498   ┆ Nightmare  ┆ 가위      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 5978      ┆ 40368   ┆ Nightmare  ┆ Nightmare ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 742       ┆ 64524   ┆ Nightmare  ┆ Nightmare ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 4878      ┆ 39498   ┆ Nightmare  ┆ 가위      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ …         ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 7256      ┆ 177121  ┆ Nightmare  ┆ 青魇      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 287       ┆ 1002500 ┆ Nightmare  ┆ 黑手套    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 7099      ┆ 287084  ┆ The Town   ┆ The Town  ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ that       ┆ that      ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Dreaded    ┆ Dreaded   ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Sundown    ┆ Sundown   ┆   ┆           ┆           ┆ com…      ┆           │
│ 2134      ┆ 48197   ┆ The Town   ┆ The Town  ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ That       ┆ That      ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Dreaded    ┆ Dreaded   ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Sundown    ┆ Sundown   ┆   ┆           ┆           ┆ com…      ┆           │
│ 287       ┆ 1002500 ┆ Nightmare  ┆ 黑手套    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘