In [7]:
import polars as pl

df = pl.read_parquet("../data/gold/gold_movies.parquet")
df = df.group_by(df.columns).first()
df.head(10)

shape: (10, 49)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ master_id ┆ tmdb_id ┆ title      ┆ original_ ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_ri │
│ ---       ┆ ---     ┆ ---        ┆ title     ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ght       │
│ u32       ┆ i64     ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆         ┆            ┆ str       ┆   ┆ null      ┆ null      ┆           ┆ str       │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 7344      ┆ 119698  ┆ The        ┆ The       ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Dinosaur   ┆ Dinosaur  ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Project    ┆ Project   ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 1497      ┆ 258006  ┆ Hysteria   ┆ Hysteria  ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 4165      ┆ 1219483 ┆ Blood      ┆ Blood     ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Actually:  ┆ Actually: ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ A Murder,  ┆ A Murder, ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ They…      ┆ They…     ┆   ┆           ┆           ┆ com…      ┆           │
│ 3808      ┆ 307150  ┆ The Door   ┆ 门        ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 7117      ┆ 49690   ┆ Smile      ┆ Smile     ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 5638      ┆ 53953   ┆ The Tooth  ┆ The Tooth ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Fairy      ┆ Fairy     ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 2805      ┆ 322587  ┆ Hot        ┆ 화끈한    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Service: A ┆ 써비스:   ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Cruel      ┆ 어느      ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Hairdress… ┆ 잔인한    ┆   ┆           ┆           ┆ com…      ┆           │
│           ┆         ┆            ┆ 미용사의  ┆   ┆           ┆           ┆           ┆           │
│ 6500      ┆ 12700   ┆ Dominion:  ┆ Dominion: ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Prequel to ┆ Prequel   ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ The Exorc… ┆ to The    ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆ Exorc…    ┆   ┆           ┆           ┆ com…      ┆           │
│ 574       ┆ 254174  ┆ The Penny  ┆ The Penny ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ Dreadful   ┆ Dreadful  ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Picture    ┆ Picture   ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Sho…       ┆ Sho…      ┆   ┆           ┆           ┆ com…      ┆           │
│ 5803      ┆ 722354  ┆ The Arrang ┆ The Arran ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ ement      ┆ gement    ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
df.filter(df.is_duplicated())

shape: (0, 49)
┌───────────┬─────────┬───────┬──────────────┬───┬──────────────┬──────────────┬─────┬─────────────┐
│ master_id ┆ tmdb_id ┆ title ┆ original_tit ┆ … ┆ audience_sco ┆ critics_cons ┆ url ┆ source_righ │
│ ---       ┆ ---     ┆ ---   ┆ le           ┆   ┆ re           ┆ ensus        ┆ --- ┆ t           │
│ u32       ┆ i64     ┆ str   ┆ ---          ┆   ┆ ---          ┆ ---          ┆ str ┆ ---         │
│           ┆         ┆       ┆ str          ┆   ┆ null         ┆ null         ┆     ┆ str         │
╞═══════════╪═════════╪═══════╪══════════════╪═══╪══════════════╪══════════════╪═════╪═════════════╡
└───────────┴─────────┴───────┴──────────────┴───┴──────────────┴──────────────┴─────┴─────────────┘

In [8]:
df.schema

Schema([('master_id', UInt32),
        ('tmdb_id', Int64),
        ('title', String),
        ('original_title', String),
        ('overview', String),
        ('release_date', String),
        ('vote_average', Float64),
        ('vote_count', Int32),
        ('popularity', Float64),
        ('original_language', String),
        ('adult', Boolean),
        ('poster_path', String),
        ('backdrop_path', String),
        ('genre_ids', List(Int64)),
        ('source', String),
        ('year', Int32),
        ('title_clean', String),
        ('title_key', String),
        ('imdb_id', String),
        ('title_imdb', String),
        ('genres', String),
        ('cast', List(String)),
        ('source_imdb', String),
        ('title_clean_imdb', String),
        ('title_kaggle', String),
        ('overview_kaggle', String),
        ('tagline', String),
        ('genres_kaggle', String),
        ('release_date_kaggle', String),
        ('vote_average_kaggle', Float64),
        ('popularity_kaggle', Float64),
        ('source_kaggle', String),
        ('title_clean_kaggle', String),
        ('movieId', Int32),
        ('title_ml', String),
        ('genres_ml', String),
        ('avg_rating', Float64),
        ('num_ratings', Int32),
        ('source_ml', String),
        ('title_clean_ml', String),
        ('fuzzy_imdb', String),
        ('fuzzy_kaggle', String),
        ('fuzzy_movielens', String),
        ('title_right', String),
        ('tomatometer_score', Null),
        ('audience_score', Null),
        ('critics_consensus', Null),
        ('url', String),
        ('source_right', String)])

In [9]:
df.describe()

shape: (9, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ master_id ┆ tmdb_id   ┆ title     ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_r │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ight     │
│ str       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 9837.0    ┆ 9837.0    ┆ 9837      ┆ … ┆ 0.0       ┆ 0.0       ┆ 9837      ┆ 9837     │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 9837.0    ┆ 9837.0    ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 4917.4559 ┆ 426810.84 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 32        ┆ 3042      ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2841.3982 ┆ 465714.23 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 56        ┆ 3524      ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 17.0      ┆ #AMFAD:   ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_t │
│           ┆           ┆           ┆ All My    ┆   ┆           ┆           ┆ ww.rotten ┆ omatoes  │
│           ┆           ┆           ┆ Friends   ┆   ┆           ┆           ┆ tomatoes. ┆          │
│           ┆           ┆           ┆ Are Dea…  ┆   ┆           ┆           ┆ com…      ┆          │
│ 25%       ┆ 2458.0    ┆ 42487.0   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 4914.0    ┆ 241843.0  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 7376.0    ┆ 697799.0  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 9846.0    ┆ 1.701736e ┆ 裸尸痕    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_t │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ omatoes  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ tomatoes. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ com…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df.group_by("master_id").len().filter(pl.col("len") > 1)

shape: (10, 2)
┌───────────┬─────┐
│ master_id ┆ len │
│ ---       ┆ --- │
│ u32       ┆ u32 │
╞═══════════╪═════╡
│ 3174      ┆ 2   │
│ 7256      ┆ 2   │
│ 3594      ┆ 2   │
│ 4368      ┆ 2   │
│ 742       ┆ 2   │
│ 287       ┆ 2   │
│ 4878      ┆ 2   │
│ 7099      ┆ 2   │
│ 2134      ┆ 2   │
│ 5978      ┆ 2   │
└───────────┴─────┘

In [11]:
dups = (
    df.group_by("master_id")
      .len()
      .filter(pl.col("len") > 1)
      .select("master_id")
)

df.filter(pl.col("master_id").is_in(dups["master_id"]))

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_29820\1464026237.py:8: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  df.filter(pl.col("master_id").is_in(dups["master_id"]))

shape: (20, 49)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ master_id ┆ tmdb_id ┆ title      ┆ original_ ┆ … ┆ audience_ ┆ critics_c ┆ url       ┆ source_ri │
│ ---       ┆ ---     ┆ ---        ┆ title     ┆   ┆ score     ┆ onsensus  ┆ ---       ┆ ght       │
│ u32       ┆ i64     ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆         ┆            ┆ str       ┆   ┆ null      ┆ null      ┆           ┆ str       │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4878      ┆ 39498   ┆ Nightmare  ┆ 가위      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 3594      ┆ 178674  ┆ Esprit     ┆ 陰陽愛    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ D'Amour    ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 4878      ┆ 39498   ┆ Nightmare  ┆ 가위      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 3174      ┆ 996067  ┆ NightMare  ┆ Mareritte ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆ t         ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 287       ┆ 1002500 ┆ Nightmare  ┆ 黑手套    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ …         ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3594      ┆ 178674  ┆ Esprit     ┆ 陰陽愛    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ D'Amour    ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 4368      ┆ 119337  ┆ Esprit     ┆ 陰陽錯    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ D'amour    ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 7256      ┆ 177121  ┆ Nightmare  ┆ 青魇      ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 287       ┆ 1002500 ┆ Nightmare  ┆ 黑手套    ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ com…      ┆           │
│ 7099      ┆ 287084  ┆ The Town   ┆ The Town  ┆ … ┆ null      ┆ null      ┆ https://w ┆ rotten_to │
│           ┆         ┆ that       ┆ that      ┆   ┆           ┆           ┆ ww.rotten ┆ matoes    │
│           ┆         ┆ Dreaded    ┆ Dreaded   ┆   ┆           ┆           ┆ tomatoes. ┆           │
│           ┆         ┆ Sundown    ┆ Sundown   ┆   ┆           ┆           ┆ com…      ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘